name: "🐞 Bug Report"
description: "Report a bug or crash in CraftoGram."
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve CraftoGram! Please fill out the following template as completely as possible.

  - type: input
    id: minecraft_version
    attributes:
      label: "Minecraft Version"
      description: "Which Minecraft version are you using? (e.g., 1.21.1)"
      placeholder: "1.21.1"
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: "CraftoGram Version"
      description: "Which version of CraftoGram are you using?"
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: loader
    attributes:
      label: "Loader"
      description: "Which loader are you using? (NeoForge, Forge, etc.)"
      placeholder: "NeoForge 21.1.211"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps needed to reproduce the bug."
      placeholder: "1. Do this\n2. Then do that\n3. Crash occurs"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "The message should be sent to Telegram without crashing."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Server crashes with NoClassDefFoundError."

  - type: textarea
    id: logs
    attributes:
      label: "Crash Logs / Error Messages"
      description: "Attach logs or crash reports (copy/paste from /logs/latest.log or /crash-reports)."
      placeholder: "Paste crash log here."

  - type: textarea
    id: config
    attributes:
      label: "Relevant Config Files"
      description: "Include relevant configuration snippets if applicable (telegram_bot_config.json, client_config.json)."
      placeholder: "Paste config here."
